export const CATEGORIES1 = [
    'Clothing',
    'Kitchen & Dining',
    'Footwear',
    'Home Decor & Festive Needs',
    'Computers',
    'Jewellery',
    'Pens & Stationery',
    'Watches',
    'Tools & Hardware',
    'Home Furnishing',
    'Bags, Wallets & Belts',
    'Beauty and Personal Care',
    'Baby Care',
    'Mobiles & Accessories',
    'Toys & School Supplies',
  ]
  
  export const CATEGORIES2 = [
    'Sports & Fitness',
    'Furniture',
    'Automotive',
    'Cameras & Accessories',
    'Home Entertainment',
    'Home Improvement',
    'Gaming',
    'Sunglasses',
    'Pet Supplies',
    'Home & Kitchen',
    'Health & Personal Care Appliances',
    'eBooks',
    'Eyewear',
    'Small Toes Bellies',
    'Household Supplies',
  ]