import Head from 'next/head'
import ProfileEdit from '../Components/Profile/ProfileEdit'
import { Box } from '@chakra-ui/react'

export default function Profile() {
  return (
    <>
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Box px="1em" w="80vw" h="80vh">
            <ProfileEdit/>
        </Box>
      </main>
    </>
  )
}