import React from 'react'
import Pagination from '../Components/Pagination/Pagination'
import ProductsTable from '../Components/Inventory/ProductsTable'
import Loader from '../Components/Loader'
import ErrorIndicator from '../Components/Error'
import AddProduct from '../Components/Inventory/AddProducts/AddProduct'
import Head from 'next/head'

import { Box, Flex } from '@chakra-ui/react'
import { PRODUCTS_ACTIONS, STATE_ACTIONS } from '../Redux/products/products.actions'
import { useAppDispatch, useAppSelector } from '../Redux/app.hooks'

const Inventory = () => {
  const {loading, error, data, count, params} = useAppSelector(store=>store.Products)
  const dispatch = useAppDispatch()
  
  React.useEffect(()=>{
    dispatch(PRODUCTS_ACTIONS.getData(params))
  }, [params])
  return (
    <>
      <Head>
        <title>Inventory</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box px="1em" w="100%" minW="80vw" h="500px">
          { 
          loading? <Loader/>:
          error? <ErrorIndicator/>:
          data && 
          <>
            <ProductsTable data={data} count={count} params={params}/>
            <Flex justify="space-between">
              {count>1 && <Pagination current={params.page} total={Math.ceil(count/params.limit)} handlePageChange={(page)=>dispatch(STATE_ACTIONS.updateParams({page}))}/>}
              <AddProduct/>
            </Flex>
          </>
          }
        </Box>
      </main>
    </>
    
  )
}

export default Inventory
