import { Flex } from '@chakra-ui/react'
import React from 'react'
import Login from '../Components/Login/Login'
import Head from 'next/head'

const LoginPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{width:"100%", height:"80vh"}}>
        <Flex h="80vh" w="100%" justify="center" align="center" mt={{base:'20vh', lg:"0"}}>
          <Login/>
        </Flex>
      </main>
    </>
    
  )
}

export default LoginPage